name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year  # or full-year
          # Add other plugins and configurations here

      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-anilist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: zeropoint25  # Replace with your Anilist username
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching, reading
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_shuffle: yes
          config_timezone: Asia/Jakarta